### ISSUE TITLE
Routing Testing

### ISSUE THREAD

**Issue by lauana-oh** [placetopay-org/code-guidelines#1]
No sería contra-productivo usar "plain routes" en los testes?

Yo entiendo que el concepto es interesante en términos de legibilidad, pero si en el futuro las rutas cambian sería un tanto engorroso hacer el cambio en cada uno de los testes mientras el mismo problema no se generaría al usar los nombres de las rutas. No les parece?

**Comment by eduarguz** [comment]
Hola @lau-hubler

Sí, este fue un punto con bastantes dudas.

Los motivos principales fueron:

## Cuando usas "Plain Routes"

```php
$this->get('/payment-methods')->assertOk();
```

1. La ruta se conoce directamente en el test, lo que ayuda con la legibilidad del test y conocimiento de la interfaz expuesta por la aplicación

   ```php
   $this->get('/payment-methods')
   $this->get('/payment-methods/1')
   $this->get('/payment-methods/200/settings')
   $this->get('/payment-methods/200/settings/abcd-uuid-1234')

   // VS

   $this->get(route('payment-methods.index'))
   $this->get(route('payment-methods.show', ['id' => '1']))
   $this->get(route('payment-methods.settings.index', ['paymentMethodId' => '200']))
   $this->get(route('payment-methods.settings.show', ['paymentMethodId' => '200', 'settingUuid' => 'abcd-uuid-1234']))
   ```
   En algunos casos usar la ruta literal puede ser más fácil de leer.
   
2. Cuando vas a escribir ese test, lo que estás testeando es ese endpoint.

   En este caso el test se basa en un dato generico (un string) `/payment-methods` lo que asegura que el dato siempre va a ser ese. A diferencia de cuando usas una función/helper `route('payment-methods.index')` se desconoce lo que pueda retornar esa función. 
   
   Desde un punto de vista muy estricto si quisieras usar el helper, debería existir otro test que se asegure de que ese helper funciona como lo esperas.

   ```php
   $this->assertEquals('/payment-methods', route('payment-methods.index'));
   ```

   Esto aseguraría que tus helpers, funcionan como esperas que funcionen.
   
   Esto es algo __muy__ estricto que en realidad no se cumple mucho, por ejemplo también se deberían testear los factories y otros helpers que usamos para escribir tests.
   

3. Si una ruta cambia, estás haciendo un gran cambio en la interfaz o api de tu aplicación, un cambio que afecta cualquier cliente que esté integrado con ese endpoint y que podría generar errores. 

   Estos errores es mejor detectarlos en las pruebas  y corregirlos así tome un poco de trabajo. 
   
   Si se usa el helper, no habría que hacer ningún cambio en los test, lo que es grandioso porque no tengo que hacer cambios en los test, pero no me muestra exactamente el impacto que está teniendo mi cambio.
   
Aún así, creo que la facilidad y utilidad del helper `route()` tambien es muy válida y no descarto la posibilidad de que muchos tengamos preferencia por esa opción, tal que cambiemos la sugerencia.

Qué opinas?

**Comment by lauana-oh** [comment]
Si me preguntas yo creo que declarar las variables con el route es más legible. Si miramos el ejemplo

```php
$this->get('/payment-methods/200/settings/abcd-uuid-1234');
$this->get(route('payment-methods.settings.show', ['paymentMethodId' => '200', 'settingUuid' => 'abcd-uuid-1234']));
```

yo sé exactamente que es 200 y abcd-uuid-1234 en el segundo caso, ahora en la ruta plana yo supongo que abcd-uuid-1234 es setting pero solo por mirar no tengo como saber que es un settingUUid. Las urls terminan siendo más sencillas por UX pero usando el route puedo tener un nombre de variable más claro. Además de la facilidad de refactorizar cuando necesario.

Sin contar que tengo declarado en el nombre de la ruta cual es la acción que corresponde. Me parece más legible:
```php
$this->get(route('payment-methods.index'));
$this->post(route('payment-methods.store'));
```

de qué tener que fijarse en el tipo de petición http:
```php
$this->get('/payment-methods');
$this->post('/payment-methods');
```

Qué opinas?

**Comment by egarcam** [comment]
Concuerdo con la apreciación de @lau-hubler por:
- claridad en argumentos / facilidad en lectura del código
- facilidad de refactorización
- menos propensión al error

**Comment by eduarguz** [comment]
Vale, creo que son argumentos suficientes para que podamos cambiar la observación. 
Muchas gracias por opinar

**Comment by eduarguz** [comment]
Actualizado!
